1

diff --git a/.github/workflows/build-x86-64-25.12.x.yml b/.github/workflows/build-x86-64-25.12.x.yml
--- a/.github/workflows/build-x86-64-25.12.x.yml
+++ b/.github/workflows/build-x86-64-25.12.x.yml
@@ -8,9 +8,9 @@ on:
         default: "25.12.0"
         type: choice
         options:
-          - 25.12.0-rc1
-          - 25.12.0-rc2
-          - 25.12.0
+        - 25.12
+        - 25.12.0
+        - 25.12.1
       custom_router_ip:
         description: "请设置路由器的管理地址(仅对多网口路由器有效) 格式:192.168.x.1 或 10.x.x.1"
         required: true
@@ -31,8 +31,8 @@ on:
         default: 'yes'
         type: choice
         options:
-          - 'yes'
-          - 'no'
+        - 'yes'
+        - 'no'
       enable_pppoe:
         description: "是否配置PPPoE拨号信息?"
         required: true
@@ -56,86 +56,85 @@ jobs:
     runs-on: ubuntu-22.04
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
+    - name: Checkout code
+      uses: actions/checkout@v6
 
-      - name: Set executable permissions
-        run: chmod +x ${{ github.workspace }}/x86-64/build25.sh
+    - name: Set executable permissions
+      run: chmod +x ${{ github.workspace }}/x86-64/build25.sh
 
-      - name: Save Custom Router IP into OpenWrt files
-        run: |
-          mkdir -p "${{ github.workspace }}/custom"
-          echo "${{ github.event.inputs.custom_router_ip }}" > "${{ github.workspace }}/custom/custom_router_ip.txt"
-          echo "您设置的路由器管理地址是:${{ github.event.inputs.custom_router_ip }}"
-          # 后续步骤会将该文件映射到路由器/etc/config/custom_router_ip.txt 以便用于开机脚本99-custom.sh读取用户设置的ip
-      
-      - name: Validate PPPoE Inputs
-        run: |
-          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
-            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
-              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
-              exit 1
-            fi
+    - name: Save Custom Router IP into OpenWrt files
+      run: |
+        mkdir -p "${{ github.workspace }}/custom"
+        echo "${{ github.event.inputs.custom_router_ip }}" > "${{ github.workspace }}/custom/custom_router_ip.txt"
+        echo "您设置的路由器管理地址是:${{ github.event.inputs.custom_router_ip }}"
+        # 后续步骤会将该文件映射到路由器/etc/config/custom_router_ip.txt 以便用于开机脚本99-custom.sh读取用户设置的ip
+
+    - name: Validate PPPoE Inputs
+      run: |
+        if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
+          if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
+            echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
+            exit 1
           fi
-      
-      - name: Enable Store integration
-        run: |
-          if [ "${{ github.event.inputs.enable_store }}" == "true" ]; then
-            echo 'CUSTOM_PACKAGES="$CUSTOM_PACKAGES luci-app-store"' >> shell/apk-custom-packages.sh
-            echo "✅ 已追加 luci-app-store"
-          else
-            echo "❎ 未启用 luci-app-store"
-          fi
+        fi
 
-      - name: Build ImmortalWrt-x86-64-efi 25.12.x
-        run: |
-          profile="${{ github.event.inputs.profile }}"
-          include_docker="${{ github.event.inputs.include_docker }}"
-          luci_version="${{ github.event.inputs.luci_version }}"
-          echo "Building for profile: $profile"
-          docker run --rm -i \
-            --user root \
-            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
-            -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
-            -v "${{ github.workspace }}/custom:/home/build/immortalwrt/files/etc/config" \
-            -v "${{ github.workspace }}/x86-64/imm25.config:/home/build/immortalwrt/.config" \
-            -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
-            -v "${{ github.workspace }}/x86-64/build25.sh:/home/build/immortalwrt/build.sh" \
-            -e PROFILE=$profile \
-            -e INCLUDE_DOCKER=$include_docker \
-            -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
-            -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
-            -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
-          immortalwrt/imagebuilder:x86-64-openwrt-${luci_version} /bin/bash /home/build/immortalwrt/build.sh
-          
+    - name: Enable Store integration
+      run: |
+        if [ "${{ github.event.inputs.enable_store }}" == "true" ]; then
+          echo 'CUSTOM_PACKAGES="$CUSTOM_PACKAGES luci-app-store"' >> shell/apk-custom-packages.sh
+          echo "✅ 已追加 luci-app-store"
+        else
+          echo "❎ 未启用 luci-app-store"
+        fi
 
-      - name: Create info
-        run: |
-          cat > ${{ github.workspace }}/router-info.md <<EOF
-          ## 📡 路由器后台信息
-          <a href="https://wkdaily.cpolar.cn/archives/1">
-           <img src="https://img.shields.io/badge/若下载慢可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
-          </a>
-          
-          - 🏠 **后台地址**: ${{ github.event.inputs.custom_router_ip }}
-          - 👤 **用户名**: root
-          - 🔑 **密码**: 无
-          EOF
+    - name: Build ImmortalWrt-x86-64-efi 25.12.x
+      run: |
+        profile="${{ github.event.inputs.profile }}"
+        include_docker="${{ github.event.inputs.include_docker }}"
+        luci_version="${{ github.event.inputs.luci_version }}"
+        echo "Building for profile: $profile"
+        docker run --rm -i \
+          --user root \
+          -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
+          -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
+          -v "${{ github.workspace }}/custom:/home/build/immortalwrt/files/etc/config" \
+          -v "${{ github.workspace }}/x86-64/imm25.config:/home/build/immortalwrt/.config" \
+          -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
+          -v "${{ github.workspace }}/x86-64/build25.sh:/home/build/immortalwrt/build.sh" \
+          -e PROFILE=$profile \
+          -e INCLUDE_DOCKER=$include_docker \
+          -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
+          -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
+          -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
+        immortalwrt/imagebuilder:x86-64-openwrt-${luci_version} /bin/bash /home/build/immortalwrt/build.sh
 
-          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
-            extra_content="#### 默认带docker"
-            echo -e "\n$extra_content" >> ${{ github.workspace }}/router-info.md
-          else
-            echo -e "\n#### 不带docker" >> ${{ github.workspace }}/router-info.md
-          fi
+    - name: Create info
+      run: |
+        cat > ${{ github.workspace }}/router-info.md <<EOF
+        ## 📡 路由器后台信息
+        <a href="https://wkdaily.cpolar.cn/archives/1">
+         <img src="https://img.shields.io/badge/若下载慢可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
+        </a>
 
-      - name: Upload ImmortWrt as release assets
-        uses: softprops/action-gh-release@v3
-        with:
-          tag_name: Autobuild-x86-64
-          body_path: ${{ github.workspace }}/router-info.md
-          files: |
-            ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz
-          token: ${{ secrets.GITHUB_TOKEN }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        - 🏠 **后台地址**: ${{ github.event.inputs.custom_router_ip }}
+        - 👤 **用户名**: root
+        - 🔑 **密码**: 无
+        EOF
+
+        if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
+          extra_content="#### 默认带docker"
+          echo -e "\n$extra_content" >> ${{ github.workspace }}/router-info.md
+        else
+          echo -e "\n#### 不带docker" >> ${{ github.workspace }}/router-info.md
+        fi
+
+    - name: Upload ImmortWrt as release assets
+      uses: softprops/action-gh-release@v3
+      with:
+        tag_name: Autobuild-x86-64
+        body_path: ${{ github.workspace }}/router-info.md
+        files: |
+          ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz
+        token: ${{ secrets.GITHUB_TOKEN }}
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
